#!/usr/bin/env python3
"""
CuZr-MD-DMS pilot runner.

This script generates and optionally runs a first MD-DMS workflow for Cu-Zr glass.

Current runtime potentials:
  mace_c:
    models/mace/mace_C.model-mliap_lammps.pt
    LAMMPS: pair_style mliap unified ... 0
  eam_cuzr:
    models/eam/cuzr_eam.fs -> Cu-Zr_4.eam.fs
    LAMMPS: pair_style eam/fs

This is a technical/pilot runner, not the final production campaign engine.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import random
import shlex
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable

AMU_TO_G = 1.66053906660e-24
CM3_TO_A3 = 1.0e24
CU_MASS = 63.546
ZR_MASS = 91.224

REPO_ROOT = Path(__file__).resolve().parents[2]


@dataclass(frozen=True)
class Preset:
    name: str
    melt_ps: float
    quench_rate_K_per_ps: float
    relax_ps: float
    equilibrate_ps: float
    mddms_period_ps: float
    mddms_cycles: int
    thermo_every_steps: int
    stress_every_steps: int
    dump_every_steps: int


PRESETS: dict[str, Preset] = {
    "tiny": Preset(
        name="tiny",
        melt_ps=1.0,
        quench_rate_K_per_ps=2700.0,
        relax_ps=1.0,
        equilibrate_ps=1.0,
        mddms_period_ps=1.0,
        mddms_cycles=2,
        thermo_every_steps=100,
        stress_every_steps=10,
        dump_every_steps=100,
    ),
    "pilot": Preset(
        name="pilot",
        melt_ps=20.0,
        quench_rate_K_per_ps=135.0,
        relax_ps=10.0,
        equilibrate_ps=10.0,
        mddms_period_ps=10.0,
        mddms_cycles=3,
        thermo_every_steps=500,
        stress_every_steps=20,
        dump_every_steps=1000,
    ),
    "ch3": Preset(
        name="ch3",
        melt_ps=1000.0,
        quench_rate_K_per_ps=1.0,
        relax_ps=100.0,
        equilibrate_ps=0.0,
        mddms_period_ps=50.0,
        mddms_cycles=30,
        thermo_every_steps=1000,
        stress_every_steps=10,
        dump_every_steps=1000,
    ),
}


MODEL_ALIASES: dict[str, dict[str, str]] = {
    "mace_c": {
        "kind": "mace",
        "path": "models/mace/mace_C.model-mliap_lammps.pt",
        "description": "MACE_C converted to LAMMPS ML-IAP format",
    },
    "eam_cuzr": {
        "kind": "eam_fs",
        "path": "models/eam/cuzr_eam.fs",
        "description": "Cu-Zr_4.eam.fs EAM/FS reference potential",
    },
}


@dataclass
class RunConfig:
    run_name: str
    run_dir: str
    preset: str
    model_alias: str
    model_kind: str
    model_file: str
    natoms: int
    cu_fraction: float
    density_g_cm3: float
    seed: int
    timestep_ps: float
    temperature_high_K: float
    temperature_low_K: float
    pressure_bar: float
    strain_amplitude: float
    tdamp_ps: float
    pdamp_ps: float
    dump_atomic: bool
    dump_voronoi: bool
    stress_sign: float
    lmp_command: str


def project_path(path_like: str | Path) -> Path:
    path = Path(path_like).expanduser()
    if path.is_absolute():
        return path
    return (REPO_ROOT / path).resolve()


def ps_to_steps(ps: float, timestep_ps: float) -> int:
    return max(0, int(round(ps / timestep_ps)))


def composition_counts(natoms: int, cu_fraction: float) -> tuple[int, int]:
    n_cu = int(round(natoms * cu_fraction))
    n_cu = min(max(n_cu, 0), natoms)
    n_zr = natoms - n_cu
    return n_cu, n_zr


def estimate_box_length_a(n_cu: int, n_zr: int, density_g_cm3: float) -> float:
    mass_g = (n_cu * CU_MASS + n_zr * ZR_MASS) * AMU_TO_G
    volume_cm3 = mass_g / density_g_cm3
    volume_a3 = volume_cm3 * CM3_TO_A3
    return volume_a3 ** (1.0 / 3.0)


def write_initial_data(path: Path, natoms: int, cu_fraction: float, density_g_cm3: float, seed: int) -> dict:
    rng = random.Random(seed)
    n_cu, n_zr = composition_counts(natoms, cu_fraction)
    L = estimate_box_length_a(n_cu, n_zr, density_g_cm3)

    ngrid = math.ceil(natoms ** (1.0 / 3.0))
    spacing = L / ngrid

    positions: list[tuple[float, float, float]] = []
    for ix in range(ngrid):
        for iy in range(ngrid):
            for iz in range(ngrid):
                if len(positions) >= natoms:
                    break
                jitter = 0.12 * spacing
                x = (ix + 0.5) * spacing + rng.uniform(-jitter, jitter)
                y = (iy + 0.5) * spacing + rng.uniform(-jitter, jitter)
                z = (iz + 0.5) * spacing + rng.uniform(-jitter, jitter)
                positions.append((x % L, y % L, z % L))
            if len(positions) >= natoms:
                break
        if len(positions) >= natoms:
            break

    atom_types = [1] * n_cu + [2] * n_zr
    rng.shuffle(atom_types)

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write("Cu-Zr initial structure generated by run_mddms_pilot.py\n\n")
        f.write(f"{natoms} atoms\n")
        f.write("2 atom types\n\n")
        f.write(f"0.0 {L:.10f} xlo xhi\n")
        f.write(f"0.0 {L:.10f} ylo yhi\n")
        f.write(f"0.0 {L:.10f} zlo zhi\n\n")
        f.write("Masses\n\n")
        f.write(f"1 {CU_MASS:.8f} # Cu\n")
        f.write(f"2 {ZR_MASS:.8f} # Zr\n\n")
        f.write("Atoms # atomic\n\n")
        for atom_id, (atype, (x, y, z)) in enumerate(zip(atom_types, positions), start=1):
            f.write(f"{atom_id} {atype} {x:.10f} {y:.10f} {z:.10f}\n")

    return {
        "natoms": natoms,
        "n_cu": n_cu,
        "n_zr": n_zr,
        "cu_fraction_actual": n_cu / natoms,
        "zr_fraction_actual": n_zr / natoms,
        "density_g_cm3": density_g_cm3,
        "box_length_A": L,
        "grid": ngrid,
        "spacing_A": spacing,
    }


def potential_block(model_kind: str, model_file: Path) -> str:
    model_file = model_file.resolve()

    if model_kind == "mace":
        return f"""# MACE via LAMMPS ML-IAP unified interface
pair_style      mliap unified {model_file} 0
pair_coeff      * * Cu Zr
"""

    if model_kind == "eam_fs":
        return f"""# EAM/FS baseline
pair_style      eam/fs
pair_coeff      * * {model_file} Cu Zr
"""

    raise ValueError(f"Unsupported model_kind: {model_kind}")


def common_header(data_file: str, model_kind: str, model_file: Path) -> str:
    return f"""units           metal
atom_style      atomic
boundary        p p p
newton          on

read_data       {data_file}

{potential_block(model_kind, model_file)}

neighbor        2.0 bin
neigh_modify    delay 0 every 1 check yes
"""


def write_prepare_input(run_dir: Path, cfg: RunConfig, preset: Preset) -> None:
    melt_steps = ps_to_steps(preset.melt_ps, cfg.timestep_ps)
    quench_ps = (cfg.temperature_high_K - cfg.temperature_low_K) / preset.quench_rate_K_per_ps
    quench_steps = ps_to_steps(quench_ps, cfg.timestep_ps)

    text = f"""{common_header("initial.data", cfg.model_kind, Path(cfg.model_file))}
timestep        {cfg.timestep_ps:.8f}

thermo          {preset.thermo_every_steps}
thermo_style    custom step time temp pe ke etotal press pxx pyy pzz pxy lx ly lz

minimize        1.0e-6 1.0e-8 1000 10000

velocity        all create {cfg.temperature_high_K:.6f} {cfg.seed + 101} mom yes rot yes dist gaussian

fix             melt all nvt temp {cfg.temperature_high_K:.6f} {cfg.temperature_high_K:.6f} {cfg.tdamp_ps:.6f}
run             {melt_steps}
unfix           melt

fix             quench all nvt temp {cfg.temperature_high_K:.6f} {cfg.temperature_low_K:.6f} {cfg.tdamp_ps:.6f}
run             {quench_steps}
unfix           quench

write_data      00_after_quench.data
write_restart   00_after_quench.restart
"""
    (run_dir / "00_prepare_melt_quench.in").write_text(text, encoding="utf-8")


def write_relax_input(run_dir: Path, cfg: RunConfig, preset: Preset) -> None:
    relax_steps = ps_to_steps(preset.relax_ps, cfg.timestep_ps)
    text = f"""{common_header("00_after_quench.data", cfg.model_kind, Path(cfg.model_file))}
timestep        {cfg.timestep_ps:.8f}

thermo          {preset.thermo_every_steps}
thermo_style    custom step time temp pe ke etotal press pxx pyy pzz pxy lx ly lz

velocity        all create {cfg.temperature_low_K:.6f} {cfg.seed + 202} mom yes rot yes dist gaussian

fix             relax all npt temp {cfg.temperature_low_K:.6f} {cfg.temperature_low_K:.6f} {cfg.tdamp_ps:.6f} iso {cfg.pressure_bar:.6f} {cfg.pressure_bar:.6f} {cfg.pdamp_ps:.6f}
run             {relax_steps}
unfix           relax

write_data      01_after_relax_npt.data
write_restart   01_after_relax_npt.restart
"""
    (run_dir / "01_relax_npt.in").write_text(text, encoding="utf-8")


def write_equilibrate_input(run_dir: Path, cfg: RunConfig, preset: Preset) -> None:
    eq_steps = ps_to_steps(preset.equilibrate_ps, cfg.timestep_ps)
    text = f"""{common_header("01_after_relax_npt.data", cfg.model_kind, Path(cfg.model_file))}
timestep        {cfg.timestep_ps:.8f}

thermo          {preset.thermo_every_steps}
thermo_style    custom step time temp pe ke etotal press pxx pyy pzz pxy lx ly lz

velocity        all create {cfg.temperature_low_K:.6f} {cfg.seed + 303} mom yes rot yes dist gaussian

fix             eq all nvt temp {cfg.temperature_low_K:.6f} {cfg.temperature_low_K:.6f} {cfg.tdamp_ps:.6f}
run             {eq_steps}
unfix           eq

write_data      02_after_equilibrate_nvt.data
write_restart   02_after_equilibrate_nvt.restart
"""
    (run_dir / "02_equilibrate_nvt.in").write_text(text, encoding="utf-8")


def write_mddms_input(run_dir: Path, cfg: RunConfig, preset: Preset) -> None:
    mddms_ps = preset.mddms_period_ps * preset.mddms_cycles
    mddms_steps = ps_to_steps(mddms_ps, cfg.timestep_ps)

    atomic_dump = ""
    if cfg.dump_atomic:
        if cfg.dump_voronoi:
            atomic_dump = f"""
compute         atomstress all stress/atom NULL
compute         atomvol all voronoi/atom
dump            atomdump all custom {preset.dump_every_steps} atom_stress.lammpstrj id type x y z c_atomstress[4] c_atomvol[1]
dump_modify     atomdump sort id
"""
        else:
            atomic_dump = f"""
compute         atomstress all stress/atom NULL
dump            atomdump all custom {preset.dump_every_steps} atom_stress.lammpstrj id type x y z c_atomstress[4]
dump_modify     atomdump sort id
"""

    text = f"""{common_header("02_after_equilibrate_nvt.data", cfg.model_kind, Path(cfg.model_file))}
timestep        {cfg.timestep_ps:.8f}

change_box      all triclinic

reset_timestep  0
velocity        all create {cfg.temperature_low_K:.6f} {cfg.seed + 404} mom yes rot yes dist gaussian

thermo          {preset.thermo_every_steps}
thermo_style    custom step time temp pe ke etotal press pxx pyy pzz pxy lx ly lz xy

variable        gamma0 equal {cfg.strain_amplitude:.12f}
variable        period equal {preset.mddms_period_ps:.12f}
variable        omega equal 2.0*{math.pi:.16f}/v_period
variable        gamma equal v_gamma0*sin(v_omega*time)
variable        gammadot equal v_gamma0*v_omega*cos(v_omega*time)
variable        xy_target equal v_gamma*ly
variable        xy_rate equal v_gammadot*ly

fix             thermostat all nvt temp {cfg.temperature_low_K:.6f} {cfg.temperature_low_K:.6f} {cfg.tdamp_ps:.6f}
fix             deform all deform 1 xy variable v_xy_target v_xy_rate remap x

variable        time_ps equal time
variable        pxy_bar equal pxy
variable        temp_K equal temp
variable        pe_eV equal pe
variable        ke_eV equal ke
variable        press_bar equal press
variable        xy_A equal xy
variable        ly_A equal ly

fix             ts all ave/time {preset.stress_every_steps} 1 {preset.stress_every_steps} v_time_ps v_gamma v_pxy_bar v_temp_K v_pe_eV v_ke_eV v_press_bar v_xy_A v_ly_A file stress_timeseries.dat
{atomic_dump}
run             {mddms_steps}

unfix           ts
unfix           deform
unfix           thermostat

write_data      03_after_mddms.data
write_restart   03_after_mddms.restart
"""
    (run_dir / "03_mddms_shear.in").write_text(text, encoding="utf-8")


def write_run_shell_script(run_dir: Path, cfg: RunConfig) -> None:
    stages = [
        "00_prepare_melt_quench.in",
        "01_relax_npt.in",
        "02_equilibrate_nvt.in",
        "03_mddms_shear.in",
    ]

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "if [ -f /workspace/cuzr_mddms_runtime.env ]; then",
        "  source /workspace/cuzr_mddms_runtime.env",
        "fi",
        "",
        f"LMP_CMD={shlex.quote(cfg.lmp_command)}",
        "",
        "run_stage() {",
        "  local input=\"$1\"",
        "  local log=\"${input%.in}.log\"",
        "  echo \"[run] $input -> $log\"",
        "  ${LMP_CMD} -log \"$log\" -in \"$input\"",
        "}",
        "",
    ]
    for stage in stages:
        lines.append(f"run_stage {shlex.quote(stage)}")
    lines.append("")

    script = run_dir / "run_lammps.sh"
    script.write_text("\n".join(lines), encoding="utf-8")
    os.chmod(script, 0o755)


def default_lmp_command(model_kind: str) -> str:
    if model_kind == "mace":
        return os.environ.get("LMP_MACE_KOKKOS_CMD", "lmp -k on g 1 -sf kk -pk kokkos newton on neigh half")
    return os.environ.get("LMP_EAM_CMD", "lmp")


def run_lammps_stage(run_dir: Path, input_file: str, lmp_command: str) -> None:
    cmd = shlex.split(lmp_command) + ["-log", input_file.replace(".in", ".log"), "-in", input_file]
    print("[execute]", " ".join(shlex.quote(x) for x in cmd), flush=True)
    subprocess.run(cmd, cwd=run_dir, check=True)


def execute_stages(run_dir: Path, cfg: RunConfig) -> None:
    for stage in [
        "00_prepare_melt_quench.in",
        "01_relax_npt.in",
        "02_equilibrate_nvt.in",
        "03_mddms_shear.in",
    ]:
        run_lammps_stage(run_dir, stage, cfg.lmp_command)


def parse_fix_ave_time(path: Path) -> list[list[float]]:
    rows: list[list[float]] = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            rows.append([float(x) for x in line.split()])
        except ValueError:
            continue
    return rows


def fit_mddms_response(stress_file: Path, period_ps: float, strain_amplitude: float, stress_sign: float) -> dict:
    import numpy as np

    rows = parse_fix_ave_time(stress_file)
    if not rows:
        raise RuntimeError(f"No numeric rows found in {stress_file}")

    arr = np.asarray(rows, dtype=float)
    time_ps = arr[:, 1]
    gamma = arr[:, 2]
    pxy_bar = arr[:, 3]
    stress_gpa = stress_sign * pxy_bar * 1.0e-4

    omega = 2.0 * math.pi / period_ps
    sin_t = np.sin(omega * time_ps)
    cos_t = np.cos(omega * time_ps)
    X = np.column_stack([sin_t, cos_t, np.ones_like(time_ps)])

    coeff, *_ = np.linalg.lstsq(X, stress_gpa, rcond=None)
    a_sin, b_cos, offset = coeff

    stress_amp_gpa = float(math.sqrt(a_sin * a_sin + b_cos * b_cos))
    phase_rad = float(math.atan2(b_cos, a_sin))
    g_storage_gpa = float((stress_amp_gpa / strain_amplitude) * math.cos(phase_rad))
    g_loss_gpa = float((stress_amp_gpa / strain_amplitude) * math.sin(phase_rad))

    fitted = X @ coeff
    residual = stress_gpa - fitted
    rmse_gpa = float(np.sqrt(np.mean(residual * residual)))

    return {
        "stress_file": str(stress_file),
        "n_points": int(len(time_ps)),
        "period_ps": float(period_ps),
        "strain_amplitude": float(strain_amplitude),
        "stress_sign": float(stress_sign),
        "fit_model": "stress_GPa = a*sin(omega*t) + b*cos(omega*t) + c",
        "a_sin_GPa": float(a_sin),
        "b_cos_GPa": float(b_cos),
        "offset_GPa": float(offset),
        "stress_amplitude_GPa": stress_amp_gpa,
        "phase_rad": phase_rad,
        "phase_deg": float(phase_rad * 180.0 / math.pi),
        "G_storage_GPa": g_storage_gpa,
        "G_loss_GPa": g_loss_gpa,
        "rmse_GPa": rmse_gpa,
        "mean_gamma": float(np.mean(gamma)),
        "max_abs_gamma": float(np.max(np.abs(gamma))),
        "mean_stress_GPa": float(np.mean(stress_gpa)),
    }


def resolve_model(model_alias: str, model_kind: str | None, model_file: str | None) -> tuple[str, Path, str]:
    if model_alias == "custom":
        if not model_kind or not model_file:
            raise ValueError("--model-alias custom requires --model-kind and --model-file")
        return model_kind, project_path(model_file), "custom model"

    if model_alias not in MODEL_ALIASES:
        raise ValueError(f"Unknown model alias {model_alias!r}")

    info = MODEL_ALIASES[model_alias]
    return info["kind"], project_path(info["path"]), info["description"]


def validate_model_file(model_kind: str, model_file: Path, allow_missing: bool = False) -> None:
    if not model_file.exists():
        message = (
            f"Model file does not exist: {model_file}\n"
            "Run first:\n"
            "  bash scripts/cloud/startup_mddms_runtime.sh"
        )
        if allow_missing:
            print(f"[warning] {message}", file=sys.stderr)
            return
        raise FileNotFoundError(message)

    if model_kind == "mace" and not model_file.name.endswith(".pt"):
        print(
            f"[warning] MACE model file is not a converted .pt file: {model_file}",
            file=sys.stderr,
        )


def generate_run(cfg: RunConfig, allow_missing_model: bool = False) -> None:
    preset = PRESETS[cfg.preset]
    run_dir = Path(cfg.run_dir).resolve()
    run_dir.mkdir(parents=True, exist_ok=True)

    model_file = Path(cfg.model_file)
    validate_model_file(cfg.model_kind, model_file, allow_missing=allow_missing_model)

    structure_meta = write_initial_data(
        run_dir / "initial.data",
        cfg.natoms,
        cfg.cu_fraction,
        cfg.density_g_cm3,
        cfg.seed,
    )

    write_prepare_input(run_dir, cfg, preset)
    write_relax_input(run_dir, cfg, preset)
    write_equilibrate_input(run_dir, cfg, preset)
    write_mddms_input(run_dir, cfg, preset)
    write_run_shell_script(run_dir, cfg)

    quench_ps = (cfg.temperature_high_K - cfg.temperature_low_K) / preset.quench_rate_K_per_ps

    metadata = {
        "run_config": asdict(cfg),
        "preset": asdict(preset),
        "derived": {
            "melt_steps": ps_to_steps(preset.melt_ps, cfg.timestep_ps),
            "quench_ps": quench_ps,
            "quench_steps": ps_to_steps(quench_ps, cfg.timestep_ps),
            "relax_steps": ps_to_steps(preset.relax_ps, cfg.timestep_ps),
            "equilibrate_steps": ps_to_steps(preset.equilibrate_ps, cfg.timestep_ps),
            "mddms_total_ps": preset.mddms_period_ps * preset.mddms_cycles,
            "mddms_steps": ps_to_steps(preset.mddms_period_ps * preset.mddms_cycles, cfg.timestep_ps),
        },
        "initial_structure": structure_meta,
    }
    (run_dir / "metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    print(f"[ok] Generated run directory: {run_dir}")
    for name in [
        "initial.data",
        "00_prepare_melt_quench.in",
        "01_relax_npt.in",
        "02_equilibrate_nvt.in",
        "03_mddms_shear.in",
        "run_lammps.sh",
        "metadata.json",
    ]:
        print(f"  - {run_dir / name}")


def print_model_aliases() -> None:
    print("Available model aliases:")
    for alias, info in MODEL_ALIASES.items():
        path = project_path(info["path"])
        status = "OK" if path.exists() else "missing"
        print(f"  {alias:10s} kind={info['kind']:7s} status={status:7s} path={path}")
        print(f"             {info['description']}")


def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Generate and optionally run a Cu-Zr MD-DMS pilot workflow.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    p.add_argument("--run-name", default="pilot_001")
    p.add_argument("--run-root", default="runs")
    p.add_argument("--preset", choices=sorted(PRESETS), default="pilot")

    p.add_argument("--model-alias", choices=sorted(MODEL_ALIASES) + ["custom"], default="mace_c")
    p.add_argument("--model-kind", choices=["mace", "eam_fs"], default=None)
    p.add_argument("--model-file", default=None)
    p.add_argument("--list-models", action="store_true")
    p.add_argument("--allow-missing-model", action="store_true")

    p.add_argument("--natoms", type=int, default=4000)
    p.add_argument("--cu-fraction", type=float, default=0.64)
    p.add_argument("--density-g-cm3", type=float, default=7.20)
    p.add_argument("--seed", type=int, default=42)

    p.add_argument("--timestep-ps", type=float, default=0.001)
    p.add_argument("--temperature-high-K", type=float, default=3000.0)
    p.add_argument("--temperature-low-K", type=float, default=300.0)
    p.add_argument("--pressure-bar", type=float, default=0.0)

    p.add_argument("--strain-amplitude", type=float, default=0.01)
    p.add_argument("--tdamp-ps", type=float, default=0.1)
    p.add_argument("--pdamp-ps", type=float, default=1.0)

    p.add_argument("--dump-atomic", action="store_true")
    p.add_argument("--dump-voronoi", action="store_true")
    p.add_argument("--stress-sign", type=float, default=-1.0)
    p.add_argument("--lmp-command", default=None)

    p.add_argument("--execute", action="store_true")
    p.add_argument("--analyze", action="store_true")

    return p


def main(argv: Iterable[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)

    if args.list_models:
        print_model_aliases()
        return 0

    model_kind, model_file, description = resolve_model(args.model_alias, args.model_kind, args.model_file)
    lmp_command = args.lmp_command or default_lmp_command(model_kind)
    run_dir = str(Path(args.run_root) / args.run_name)

    cfg = RunConfig(
        run_name=args.run_name,
        run_dir=run_dir,
        preset=args.preset,
        model_alias=args.model_alias,
        model_kind=model_kind,
        model_file=str(model_file),
        natoms=args.natoms,
        cu_fraction=args.cu_fraction,
        density_g_cm3=args.density_g_cm3,
        seed=args.seed,
        timestep_ps=args.timestep_ps,
        temperature_high_K=args.temperature_high_K,
        temperature_low_K=args.temperature_low_K,
        pressure_bar=args.pressure_bar,
        strain_amplitude=args.strain_amplitude,
        tdamp_ps=args.tdamp_ps,
        pdamp_ps=args.pdamp_ps,
        dump_atomic=args.dump_atomic,
        dump_voronoi=args.dump_voronoi,
        stress_sign=args.stress_sign,
        lmp_command=lmp_command,
    )

    print(f"[model] alias={args.model_alias} kind={model_kind}")
    print(f"[model] file={model_file}")
    print(f"[model] {description}")
    print(f"[lammps] command={lmp_command}")

    generate_run(cfg, allow_missing_model=args.allow_missing_model)
    run_dir_path = Path(run_dir).resolve()

    if args.execute:
        execute_stages(run_dir_path, cfg)

    if args.analyze:
        preset = PRESETS[cfg.preset]
        stress_file = run_dir_path / "stress_timeseries.dat"
        if not stress_file.exists():
            raise FileNotFoundError(f"Cannot analyze: missing {stress_file}")
        fit = fit_mddms_response(
            stress_file=stress_file,
            period_ps=preset.mddms_period_ps,
            strain_amplitude=cfg.strain_amplitude,
            stress_sign=cfg.stress_sign,
        )
        fit_path = run_dir_path / "mddms_fit.json"
        fit_path.write_text(json.dumps(fit, indent=2), encoding="utf-8")
        print(f"[ok] Wrote fit: {fit_path}")
        print(json.dumps(fit, indent=2))

    print()
    print("Next commands:")
    print(f"  cd {run_dir_path}")
    print("  bash run_lammps.sh")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
